package com.nature.model.account;

import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;

// Generated 2016-1-21 19:14:55 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Business generated by hbm2java
 */
@Entity
public class SystemUser implements java.io.Serializable {

	@Id
	@Column(name = "userId", unique = true, nullable = false)
	private String userId;
	
	@Column(name = "openId")
	private String openId;
	
	@Column(name = "sessionKey")
	private String sessionKey;
	@Column(name = "nickName")
	private String nickName;
	@Column(name = "gender")
	private String gender;
	@Column(name = "language")
	private String language;
	@Column(name = "city")
	private String city;
	@Column(name = "province")
	private String province;
	@Column(name = "country")
	private String country;
	@Column(name = "avatarUrl")
	private String avatarUrl;
	@Column(name = "createTimes")
	private Date createTimes;
	@Column(name = "updateTimes")
	private Date updateTimes;
	
	@Column(name="companyAccountId")
	private String companyAccountId;
	
	@Column(name="searchHistory")
	//搜索的历史记录（每个记录以英文逗号隔开）
	private String searchHistory;
	
	
	public SystemUser()
	{}


	public String getUserId() {
		return userId;
	}


	public void setUserId(String userId) {
		this.userId = userId;
	}


	public String getOpenId() {
		return openId;
	}


	public String getSearchHistory() {
		return searchHistory;
	}


	public void setSearchHistory(String searchHistory) {
		this.searchHistory = searchHistory;
	}


	public void setOpenId(String openId) {
		this.openId = openId;
	}

	public String getSessionKey() {
		return sessionKey;
	}


	public void setSessionKey(String sessionKey) {
		this.sessionKey = sessionKey;
	}


	public String getNickName() throws UnsupportedEncodingException {
		return URLDecoder.decode(nickName, "utf-8");
	}


	public void setNickName(String nickName) {
		this.nickName = nickName;
	}


	public String getCompanyAccountId() {
		return companyAccountId;
	}


	public void setCompanyAccountId(String companyAccountId) {
		this.companyAccountId = companyAccountId;
	}


	public String getGender() {
		return gender;
	}


	public void setGender(String gender) {
		this.gender = gender;
	}


	public String getLanguage() {
		return language;
	}


	public void setLanguage(String language) {
		this.language = language;
	}


	public String getCity() {
		return city;
	}


	public void setCity(String city) {
		this.city = city;
	}


	public String getProvince() {
		return province;
	}


	public void setProvince(String province) {
		this.province = province;
	}


	public String getCountry() {
		return country;
	}


	public void setCountry(String country) {
		this.country = country;
	}


	public String getAvatarUrl() {
		return avatarUrl;
	}


	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}


	public Date getCreateTimes() {
		return createTimes;
	}


	public void setCreateTimes(Date createTimes) {
		this.createTimes = createTimes;
	}


	public Date getUpdateTimes() {
		return updateTimes;
	}


	public void setUpdateTimes(Date updateTimes) {
		this.updateTimes = updateTimes;
	}


}
